#!/bin/bash

# The values pmset understands for each mode, when not using secure virtual
# memory
sleep=0
hibernate=1
both=3

# add this to mode if using secure memory
secure=4

function print_current_mode {
    current_mode=$1
    case "$current_mode" in
        $sleep | $((sleep+secure)))
            echo sleep
            ;;
        $hibernate | $((hibernate+secure)))
            echo hibernate
            ;;
        $both | $((both+secure)))
            echo both
            ;;
        *)
            echo Error: I do not understand the current sleep mode.
            exit 1
        esac
}

function get_current_mode {
    current=`pmset -g | grep hibernatemode | awk '{print $2}'`
    return $current
}

echo -n "Current mode: "
get_current_mode
print_current_mode $?

function usage {
    echo "-s sleep, -h hibernate, -b both."
}

arg=$1

case "$arg" in
'-s')
        mode=$sleep
        ;;
'-h')
        mode=$hibernate
        ;;
'-b')
        mode=$both
        ;;
*)
        usage
        exit 1
esac

# If secure virtual memory
sysctl vm.swapusage |grep encrypted 1>/dev/null
if (($? == 0)); then
    mode=$((mode+secure))
fi


sudo pmset -a hibernatemode $mode

echo -n "Now set to: "
get_current_mode
print_current_mode $?
