#!/bin/bash

# A script to set Macbook sleep mode.
# Maintained on github:
# https://github.com/anm/Macbook-Sleep-Mode
#
# Copyright 2011, Alistair N. MacLeod 
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


# The values pmset understands for each mode, when not using secure virtual
# memory. See man pmset from OS 10.6. Undocumented in 10.4.
sleep=0
hibernate=25
both=3

function print_current_mode {
    current_mode=$1
    case "$current_mode" in
        $sleep)
            echo sleep
            ;;
        $hibernate)
            echo hibernate
            ;;
        $both)
            echo both
            ;;
        *)
            echo Error: I do not understand the current sleep mode.
        esac
}

function get_current_mode {
    current=`pmset -g | grep hibernatemode | awk '{print $2}'`
    return $current
}

echo -n "Current mode: "
get_current_mode
print_current_mode $?

function usage {
    echo "-s sleep, -h hibernate, -b both."
}

arg=$1

case "$arg" in
'-s')
        mode=$sleep
        ;;
'-h')
        mode=$hibernate
        ;;
'-b')
        mode=$both
        ;;
*)
        usage
        exit 1
esac

sudo pmset -a hibernatemode $mode

echo -n "Now set to: "
get_current_mode
print_current_mode $?
